In [3]:
import pandas as pd

In [5]:
import os

os.getcwd()

'c:\\Users\\DELL\\Downloads\\Olist_ML_Project\\notebooks'

In [6]:
import os

os.listdir("..")

['.vscode', 'notebooks']

In [8]:
orders = pd.read_csv(r"C:\Users\DELL\Downloads\olist\olist_orders_dataset.csv")

In [9]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [10]:
orders.shape

(99441, 8)

In [11]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [12]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [13]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [14]:
orders.duplicated().sum()

np.int64(0)

In [15]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [16]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [17]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [18]:
delivered = orders[orders["order_status"] == "delivered"].copy()

In [19]:
delivered["is_late"] = (
    delivered["order_delivered_customer_date"]
    > delivered["order_estimated_delivery_date"]
).astype(int)

In [20]:
delivered["is_late"].value_counts()

is_late
0    88652
1     7826
Name: count, dtype: int64

In [21]:
delivered["is_late"].value_counts()

is_late
0    88652
1     7826
Name: count, dtype: int64

In [22]:
delivered["purchase_year"] = delivered["order_purchase_timestamp"].dt.year
delivered["purchase_month"] = delivered["order_purchase_timestamp"].dt.month
delivered["purchase_day"] = delivered["order_purchase_timestamp"].dt.day
delivered["purchase_dayofweek"] = delivered["order_purchase_timestamp"].dt.dayofweek
delivered["purchase_hour"] = delivered["order_purchase_timestamp"].dt.hour

In [23]:
delivered[
    [
        "purchase_year",
        "purchase_month",
        "purchase_dayofweek",
        "purchase_hour",
        "is_late",
    ]
].head()

   purchase_year  purchase_month  purchase_dayofweek  purchase_hour  is_late
0           2017              10                   0             10        0
1           2018               7                   1             20        0
2           2018               8                   2              8        0
3           2017              11                   5             19        0
4           2018               2                   1             21        0

In [24]:
delivered["days_to_estimated_delivery"] = (
    delivered["order_estimated_delivery_date"] - delivered["order_purchase_timestamp"]
).dt.days

In [25]:
delivered[
    [
        "order_purchase_timestamp",
        "order_estimated_delivery_date",
        "days_to_estimated_delivery",
        "is_late",
    ]
].head()

,order_purchase_timestamp,order_estimated_delivery_date,days_to_estimated_delivery,is_late
0,2017-10-02 10:56:33,2017-10-18,15,0
1,2018-07-24 20:41:37,2018-08-13,19,0
2,2018-08-08 08:38:49,2018-09-04,26,0
3,2017-11-18 19:28:06,2017-12-15,26,0
4,2018-02-13 21:18:39,2018-02-26,12,0

In [26]:
delivered["delivery_days"] = (
    delivered["order_delivered_customer_date"] - delivered["order_purchase_timestamp"]
).dt.days

In [27]:
delivered[["delivery_days", "days_to_estimated_delivery", "is_late"]].head()

   delivery_days  days_to_estimated_delivery  is_late
0            8.0                          15        0
1           13.0                          19        0
2            9.0                          26        0
3           13.0                          26        0
4            2.0                          12        0

In [28]:
features = [
    "purchase_year",
    "purchase_month",
    "purchase_day",
    "purchase_dayofweek",
    "purchase_hour",
    "days_to_estimated_delivery",
]

X = delivered[features]
y = delivered["is_late"]

In [29]:
X.head()

,purchase_year,purchase_month,purchase_day,purchase_dayofweek,purchase_hour,days_to_estimated_delivery
0,2017,10,2,0,10,15
1,2018,7,24,1,20,19
2,2018,8,8,2,8,26
3,2017,11,18,5,19,26
4,2018,2,13,1,21,12

In [30]:
y.value_counts()

is_late
0    88652
1     7826
Name: count, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [34]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((77182, 6), (19296, 6), (77182,), (19296,))

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [37]:
y_pred = model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9188951077943616

In [39]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     17731
           1       0.00      0.00      0.00      1565

    accuracy                           0.92     19296
   macro avg       0.46      0.50      0.48     19296
weighted avg       0.84      0.92      0.88     19296

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     17731
           1       0.00      0.00      0.00      1565

    accuracy                           0.92     19296
   macro avg       0.46      0.50      0.48     19296
weighted avg       0.84      0.92      0.88     19296

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
rf_model = RandomForestClassifier(
    n_estimators=200, random_state=42, class_weight="balanced", n_jobs=-1
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [43]:
rf_pred = rf_model.predict(X_test)

In [44]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.94      0.89      0.91     17731
           1       0.20      0.31      0.24      1565

    accuracy                           0.85     19296
   macro avg       0.57      0.60      0.58     19296
weighted avg       0.88      0.85      0.86     19296

In [46]:
order_items = pd.read_csv(
    r"C:\Users\DELL\Downloads\olist\olist_order_items_dataset.csv"
)

In [47]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [48]:
order_item_features = (
    order_items.groupby("order_id")
    .agg(
        num_items=("order_item_id", "count"),
        total_price=("price", "sum"),
        total_freight_value=("freight_value", "sum"),
        num_sellers=("seller_id", "nunique"),
    )
    .reset_index()
)

In [49]:
order_item_features.head()

,order_id,num_items,total_price,total_freight_value,num_sellers
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,1
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,1
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,1
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,1

In [50]:
delivered = delivered.merge(order_item_features, on="order_id", how="left")

In [51]:
delivered.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_late,purchase_year,purchase_month,purchase_day,purchase_dayofweek,purchase_hour,days_to_estimated_delivery,delivery_days,num_items,total_price,total_freight_value,num_sellers
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,2017,10,2,0,10,15,8.0,1,29.99,8.72,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,2018,7,24,1,20,19,13.0,1,118.70,22.76,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,2018,8,8,2,8,26,9.0,1,159.90,19.22,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,2017,11,18,5,19,26,13.0,1,45.00,27.20,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,2018,2,13,1,21,12,2.0,1,19.90,8.72,1

In [52]:
features = [
    "purchase_year",
    "purchase_month",
    "purchase_day",
    "purchase_dayofweek",
    "purchase_hour",
    "days_to_estimated_delivery",
    "num_items",
    "total_price",
    "total_freight_value",
    "num_sellers",
]

X = delivered[features]
y = delivered["is_late"]

In [53]:
X.head()

,purchase_year,purchase_month,purchase_day,purchase_dayofweek,purchase_hour,days_to_estimated_delivery,num_items,total_price,total_freight_value,num_sellers
0,2017,10,2,0,10,15,1,29.99,8.72,1
1,2018,7,24,1,20,19,1,118.70,22.76,1
2,2018,8,8,2,8,26,1,159.90,19.22,1
3,2017,11,18,5,19,26,1,45.00,27.20,1
4,2018,2,13,1,21,12,1,19.90,8.72,1

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [55]:
X_train.shape, X_test.shape

((77182, 10), (19296, 10))

In [56]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200, random_state=42, class_weight="balanced", n_jobs=-1
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [57]:
rf_pred = rf_model.predict(X_test)

print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95     17731
           1       0.32      0.21      0.25      1565

    accuracy                           0.90     19296
   macro avg       0.63      0.58      0.60     19296
weighted avg       0.88      0.90      0.89     19296

In [58]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, rf_pred)
cm

array([[17043,   688],
       [ 1243,   322]])

In [59]:
import joblib

joblib.dump(rf_model, "rf_model.pkl")
joblib.dump(features, "features.pkl")

['features.pkl']

In [60]:
import os

os.listdir()

['01_read_and_join.ipynb', 'features.pkl', 'rf_model.pkl']

In [61]:
delivered.to_csv("labeled_orders.csv", index=False)

In [62]:
import os

os.path.exists("labeled_orders.csv")

True